### ISSUE TITLE
Why choose vector<char> as the binary stream cache

### ISSUE THREAD

**Issue by EricDDK** [simdsoft/yasio#94]
Is it inefficient?

**Comment by EricDDK** [comment]
I tried std::string, but it will be truncated due to '\0 ' when writing binary, Ask if there is a good idea

**Comment by halx99** [comment]
Actual In C++, both ```std::string``` and ```std::vector<char>``` can handle binary stream.
for std::string you can always specify length  when copy or pass parameter.
Such as:
char data[] = {'a', 'b', 'c', '\0', 'e', 'f', 'g'};
std::string sbuf(data, 7);
std::vector<char> vcbuf(data, &data[0] + 7);

**Comment by EricDDK** [comment]
> Actual In C++, both `std::string` and `std::vector<char>` can handle binary stream.
> for std::string you can always specify length when copy or pass parameter.
> Such as:
> char data[] = {'a', 'b', 'c', '\0', 'e', 'f', 'g'};
> std::string sbuf(data, 7);
> std::vector vcbuf(data, &data[0] + 7);

thank you for your reply.  :)

**Comment by halx99** [comment]
You are welcome.
And use ```std::vector<char>``` as binary stream cache may have follow reasons:
1. Avoid truncated due to '\0 ' when forget specify length.
2. The std::string at different compilers implement not same.
 For MSVC implementation: the string will have 16 bytes fixed buffer
when we store these buffer to a queue, even through theses buffers less 16 bytes, Its allways need 16bytes.
3. For binary stream concept reason, I think ```std::vector<char>``` more better.

**Comment by EricDDK** [comment]
> You are welcome.
> And use `std::vector<char>` as binary stream cache may have follow reasons:
> 
> 1. Avoid truncated due to '\0 ' when forget specify length.
> 2. The std::string at different compilers implement not same.
>    For MSVC implementation: the string will have 16 bytes fixed buffer
>    when we store these buffer to a queue, even through theses buffers less 16 bytes, Its allways need 16bytes.
> 3. For binary stream concept reason, I think `std::vector<char>` more better.

Oh no.I forgot to reply to you. Thanks man.
 I am embarrassed. Does the project contain source codes with tools/pcode_autog.exe ?
